// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddCaracterController from "./add_caracter_controller.js"
application.register("add-caracter", AddCaracterController)

import CaractersAndGroupsController from "./caracters_and_groups_controller.js"
application.register("caracters-and-groups", CaractersAndGroupsController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PickOneController from "./pick_one_controller.js"
application.register("pick-one", PickOneController)
